### ISSUE TITLE
how to use the rules file with .posthtmlrc ?

### ISSUE THREAD

**Issue by ctf0** [posthtml/posthtml-hint#23]
- if we used the object directly, it works ex.
```json
{
    "plugins": {
        "posthtml-hint": {
            "tagname-lowercase": true,
            "attr-lowercase": true,
            "attr-value-double-quotes": true,
            "attr-value-not-empty": false,
        }
    }
}
```

- but not with the config file path ex.
```json
{
    "plugins": {
        "posthtml-hint": "/path/to/.htmlhintrc"
    }
}
```

am i missing something ?

**Comment by Scrum** [comment]
@ctf0 Hi, I’ll try to deal with it tomorrow, thanks for using `posthtml` ))

**Comment by Scrum** [comment]
@ctf0 Hi, try after publish #28 

I write test with string options see https://github.com/posthtml/posthtml-hint/pull/28/commits/0a9546f7d7f66fb56e275591c678d1ac88ebb7ae

**Comment by ctf0** [comment]
awesome, thanx for ur work.

will re-open if something came up later.

**Comment by Scrum** [comment]
@ctf0 publish v0.8.3
